classDiagram
    direction LR

    OfficePerson o.. "*" LoginCredentials
    LoginCredentials "1" o-- "1" RbacSubject

    LoginContext "1..n" --o "1" LoginContextMapping
    LoginCredentials "1..n" --o "1" LoginContextMapping

    class LoginCredentials{
        +twoFactorAuth: text
        +telephonePassword: text
        +emailAdress: text
        +smsNumber: text
        -active: bool [r/w]
        -globalUid: int [w/o]
        -globalGid: int [w/o]
        -onboardingToken: text [w/o]
    }

    class LoginContext{
        -type: Enum [SSH, Matrix, Mastodon, ...]
        -qualifier: text
    }

    class LoginContextMapping{
    }
    note for LoginContextMapping "Assigns LoginCredentials to LoginContexts"

    class RbacSubject{
        +uuid: uuid
        +name: text # == nickname
    }

    class OfficePerson{
        +type: enum
        +tradename: text
        +title: text
        +familyName: text
        +givenName: text
        +salutation: text
    }

    style LoginContext fill:#00f,color:#fff
    style LoginContextMapping fill:#00f,color:#fff
    style LoginCredentials fill:#00f,color:#fff

    style RbacSubject fill:#f96,color:#fff
    style OfficePerson fill:#f66,color:#000
