# Configuration for the dev-profile using a file-based H2 database.

spring:
    profiles:
        active: h2,h2file
        include:
            - dev
            - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
    datasource:
        url: url: jdbc:h2:~/.hsadminng.h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: hsadminNg
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedH2Dialect
        database: H2
    liquibase:
        contexts: dev
