openapi: 3.0.3
info:
  title: Hostsharing hsadmin-ng API
  version: v0
servers:
  - url: http://localhost:8080
    description: Local development default URL.

paths:

  # Contexts

  /api/hs/credentials/contexts:
    $ref: "contexts.yaml"


  # Credentials

  /api/hs/credentials/credentials:
    $ref: "api-paths.yaml"

  /api/hs/credentials/credentials/{credentialsUuid}:
    $ref: "credentials-with-uuid.yaml"
