openapi: 3.0.1
info:
    title: Hostsharing hsadmin-ng API
    version: v0
servers:
    - url: http://localhost:8080
      description: Local development default URL.

paths:

    # RBAC

    /api/rbac-users:
        $ref: "./api-definition/rbac-users.yaml"

    /api/rbac-users/{userName}/permissions:
        $ref: "./api-definition/rbac-users-permissions.yaml"

    /api/rbac-roles:
        $ref: "./api-definition/rbac-roles.yaml"

    # HS

    /api/customers:
        $ref: "./api-definition/hs-customers.yaml"

    /api/packages:
        $ref: "./api-definition/hs-packages.yaml"

    /api/packages/{packageUUID}:
        $ref: "./api-definition/hs-packages-uuid.yaml"

    # Other

    /api/ping:
        get:
            tags:
                - test
            operationId: ping
            responses:
                "200":
                    description: OK
                    content:
                        'application/json':
                            schema:
                                type: string
