spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  sql:
    init:
      mode: never

liquibase:
    contexts: dev
