server:
    port : 8080

management:
    server:
        port: 8081
        address: 127.0.0.1
    endpoints:
        web:
            exposure:
                # HOWTO: view _clickable_ Spring Actuator (Micrometer) Metrics endpoints:
                #   http://localhost:8081/actuator/metric-links

                # HOWTO: view all configured endpoints of the running application:
                #   http://localhost:8081/actuator/mappings

                # HOWTO: view the effective application configuration properties:
                #   http://localhost:8081/actuator/configprops

                include: info, health, metrics, metric-links, mappings, openapi, swaggerui, configprops, env
    endpoint:
        env:
            # TODO.spec: check this, maybe set to when_authorized?
            show-values: always
        configprops:
            # TODO.spec: check this, maybe set to when_authorized?
            show-values: always
    observations:
        annotations:
            enabled: true

spring:

    datasource:
        driver-class-name: org.postgresql.Driver
        password: password
        url: ${HSADMINNG_POSTGRES_JDBC_URL}
        username: postgres

    sql:
        init:
            mode: never

    jpa:
        properties:
            hibernate:
                dialect: net.hostsharing.hsadminng.config.PostgresCustomDialect

    liquibase:
        contexts: ${spring.profiles.active}

# keep this in sync with test/.../application.yml
springdoc:
    use-management-port: true

hsadminng:
    postgres:
        leakproof:
    cas:
        server: https://login.hostsharing.net/cas # use empty string to bypass CAS-validation and directly use current-subject
        service: https://hsadminng.hostsharing.net:443 # TODO.conf: deployment target + matching CAS service ID

metrics:
    distribution:
        percentiles-histogram:
            http:
                server:
                    requests: true
