server:
    port : 8080

management:
    server:
        port: 8081
        address: 127.0.0.1
    endpoints:
        web:
            exposure:
                # HOWTO: view _clickable_ Spring Actuator (Micrometer) Metrics endpoints: http://localhost:8081/actuator/metric-links
                include: info, health, metrics, metric-links
    observations:
        annotations:
            enabled: true

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres

    sql:
        init:
            mode: never

    jpa:
        properties:
            hibernate:
                dialect: net.hostsharing.hsadminng.config.PostgresCustomDialect

liquibase:
    contexts: dev

hsadminng:
    postgres:
        leakproof:

metrics:
    distribution:
        percentiles-histogram:
            http:
                server:
                    requests: true

