server:
    port : 8080

management:
    server:
        port: 8081
        address: 127.0.0.1
    endpoints:
        web:
            exposure:
                # HOWTO: view _clickable_ Spring Actuator (Micrometer) Metrics endpoints: http://localhost:8081/actuator/metric-links
                include: info, health, metrics, metric-links, mappings, openapi, swaggerui
    observations:
        annotations:
            enabled: true

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres

    sql:
        init:
            mode: never

    jpa:
        properties:
            hibernate:
                dialect: net.hostsharing.hsadminng.config.PostgresCustomDialect

# keep this in sync with test/.../application.yml
springdoc:
    use-management-port: true

liquibase:
    contexts: dev

hsadminng:
    postgres:
        leakproof:
    cas:
        server: https://login.hostsharing.net/cas # use empty string to bypass CAS-validation and directly use current-subject
        service: https://hsadminng.hostsharing.net:443 # TODO.conf: deployment target + matching CAS service ID

metrics:
    distribution:
        percentiles-histogram:
            http:
                server:
                    requests: true

