openapi: 3.0.1
info:
    title: Hostsharing hsadmin-ng API
    version: v0
servers:
    - url: http://localhost:8080
      description: Local development default URL.

paths:

    /api/rbac/users:
        $ref: './rbac-users.yaml'

    /api/rbac/users/{userUuid}/permissions:
        $ref: './rbac-users-with-id-permissions.yaml'

    /api/rbac/users/{userUuid}:
        $ref: './rbac-users-with-uuid.yaml'

    /api/rbac/roles:
        $ref: './rbac-roles.yaml'

    /api/rbac/grants:
        $ref: './rbac-grants.yaml'

    /api/rbac/grants/{grantedRoleUuid}/{granteeUserUuid}:
        $ref: './rbac-grants-with-id.yaml'

