openapi: 3.0.3
info:
  title: Hostsharing hsadmin-ng API
  version: v0
servers:
  - url: http://localhost:8080
    description: Local development default URL.

paths:

  # Assets

  /api/hs/hosting/assets:
    $ref: "hs-hosting-assets.yaml"

  /api/hs/hosting/assets/{assetUuid}:
    $ref: "hs-hosting-assets-with-uuid.yaml"

  # Asset-Types

  /api/hs/hosting/asset-types:
    $ref: "hs-hosting-asset-types.yaml"

  /api/hs/hosting/asset-types/{assetType}:
    $ref: "hs-hosting-asset-types-props.yaml"
