openapi: 3.0.1
info:
  title: Hostsharing hsadmin-ng API
  version: v0
servers:
  - url: http://localhost:8080
    description: Local development default URL.

paths:

  /api/hs/office/partners:
    $ref: "./hs-office-partners.yaml"

  /api/hs/office/partners/{partnerUUID}:
    $ref: "./hs-office-partners-with-uuid.yaml"

