#!/bin/bash

mkdir -p src/test/java/net/hostsharing/hsadminng/hs/admin/partner

#sed -e 's/hs-admin-contact/hs-admin-partner/g' \
#	-e 's/hs_admin_contact/hs_admin_partner/g' \
#	-e 's/HsAdminContact/HsAdminPartner/g' \
#	-e 's/hsAdminContact/hsAdminPartner/g' \
#	-e 's/contact/partner/g' \
#<src/test/java/net/hostsharing/hsadminng/hs/admin/contact/HsAdminContactRepositoryIntegrationTest.java \
#>src/test/java/net/hostsharing/hsadminng/hs/admin/partner/HsAdminPartnerRepositoryIntegrationTest.java


sed -e 's/hs-admin-contact/hs-admin-partner/g' \
	-e 's/hs_admin_contact/hs_admin_partner/g' \
	<src/main/resources/db/changelog/200-hs-admin-contact.sql >src/main/resources/db/changelog/220-hs-admin-partner.sql

sed -e 's/hs-admin-contact/hs-admin-partner/g' \
	-e 's/hs_admin_contact/hs_admin_partner/g' \
	-e 's/HsAdminCustomer/HsAdminPartner/g' \
	-e 's/hsAdminContact/hsAdminPartner/g' \
	-e 's/contact/partner/g' \
	<src/main/resources/db/changelog/203-hs-admin-contact-rbac.sql >src/main/resources/db/changelog/223-hs-admin-partner-rbac.sql

sed -e 's/hs-admin-contact/hs-admin-partner/g' \
	-e 's/hs_admin_contact/hs_admin_partner/g' \
	-e 's/HsAdminContact/HsAdminPartner/g' \
	-e 's/hsAdminContact/hsAdminPartner/g' \
	-e 's/contact/partner/g' \
	<src/main/resources/db/changelog/208-hs-admin-contact-test-data.sql >src/main/resources/db/changelog/228-hs-admin-partner-test-data.sql


# mkdir -p src/main/java/net/hostsharing/hsadminng/hs/admin/partner
# 
# sed -e 's/HsAdminContactEntity/HsAdminPartnerEntity/g' \
# sed -e 's/admin.contact/admin.partner/g' \
# 	<src/main/java/net/hostsharing/hsadminng/hs/admin/contact/HsAdminContactEntity.java >src/main/java/net/hostsharing/hsadminng/hs/admin/partner/HsAdminPartnerEntity.java

cat >>src/main/resources/db/changelog/db.changelog-master.yaml <<EOF
    - include:
        file: db/changelog/220-hs-admin-partner.sql
    - include:
        file: db/changelog/223-hs-admin-partner-rbac.sql
    - include:
        file: db/changelog/228-hs-admin-partner-test-data.sql
EOF
