openapi: 3.0.1
info:
    title: Hostsharing hsadmin-ng API
    version: v0
servers:
    - url: http://localhost:8080
      description: Local development default URL.

paths:

    /api/ping:
        get:
            tags:
                - test
            operationId: ping
            responses:
                "200":
                    description: OK
                    content:
                        'application/json':
                            schema:
                                type: string
