openapi: 3.0.3
info:
  title: Hostsharing hsadmin-ng API
  version: v0
servers:
  - url: http://localhost:8080
    description: Local development default URL.

paths:

  # current

  /api/hs/accounts/current:
    $ref: "current.yaml"

  # Scopes

  /api/hs/accounts/scopes:
    $ref: "scopes.yaml"


  # Profile

  /api/hs/accounts/profiles/{profileUuid}:
    $ref: "profile-with-uuid.yaml"

  /api/hs/accounts/profiles:
    $ref: "profiles.yaml"

