openapi: 3.0.3
info:
  title: Hostsharing hsadmin-ng API
  version: v0
servers:
  - url: http://localhost:8080
    description: Local development default URL.

paths:

  # current

  /api/hs/accounts/current:
    $ref: "current.yaml"

  # Account

  /api/hs/accounts/accounts/{accountUuid}:
    $ref: "accout-with-uuid.yaml"

  /api/hs/accounts/accounts:
    $ref: "accounts.yaml"

